// GENERATED by tools/cannotSeeBlock.mjs — do not edit by hand.
// Edit the source documents, then regenerate with:
// npm run cannotsee:write
// A test compares this committed module to the generator's
// output and fails when they drift; every claim is quote-pinned
// against the exact sentence in its source document, so a source
// that changes its mind breaks the build rather than letting a
// report overstate what the instrument can do.

/** One thing this instrument cannot see, and where that is proven. */
export type CannotSeeClaim = {
  claim: string;
  source: string;
};

export const CANNOT_SEE_CLAIMS: readonly CannotSeeClaim[] = [
  {
    claim:
      "Ordinary blinks it simply misses. On the benchmark it was scored against, 67 of 408 annotated blinks — about one in six — were missed at healthy frame rates, deterministically: the same 67 blinks every run, 70.1 percent of them containing a frame a human marked fully closed. The mechanism is unexplained.",
    source: "docs/eyeblink8-result.txt; docs/miss-character.txt",
  },
  {
    claim:
      "Whether another device would agree. Two phones measured at the same evidence rate found different blinks, and that difference is unexplained, so numbers from this device are not comparable to numbers from another.",
    source: "docs/validation-dry-run.txt; docs/blink-sample-rate.txt",
  },
  {
    claim:
      "A PERCLOS anyone else would recognise. The eyes-closed share here uses an instrument-adjusted threshold, not the literature's, and is not comparable to a PERCLOS figure from another system.",
    source: "MODEL_CARD.md",
  },
  {
    claim:
      "Its own misses. A missed blink writes no row, so the blink log is censored and cannot count what it failed to see.",
    source: "docs/validation-round.txt",
  },
  {
    claim:
      "Two calibration failures invisible at birth: a learning window that reads uniformly high (the future is not available at calibration time), and a ruler born short through a squint, visible only afterwards as over_resting below 1.0 — and a ruler born short stays short, by the freeze's own stated trade.",
    source: "docs/calibration-refusal.txt; docs/baseline-freeze.txt",
  },
  {
    claim:
      "Who it fails for. The face model has not been tested across age, skin tone, eye shape, visual impairment or eyewear here, and it would be dishonest to imply equal performance.",
    source: "MODEL_CARD.md",
  },
  {
    claim:
      "Sleepiness. The alertness score is a heuristic that has never been shown to correspond to how sleepy anyone actually is; on the 20 sessions of the one labelled dataset this instrument can measure, nothing cleared the pre-registered bar. Cite: Massoz, Langohr, Francois and Verly, WACV 2016..",
    source: "MODEL_CARD.md; docs/drozy-result.txt",
  },
];
