import { BUNDLE_BUDGET_BYTES } from "./bundleBudget.mjs";
import { phasesComplete } from "./gateGuard.mjs";
import {
  actualPythonTestCount,
  actualUnitTestCount,
  parseResultFile,
  readRepoFile,
} from "./resultGuard.mjs";

// Roadmap 10.0b5, ladder D14. The September audit found eight
// documents disagreeing about where this project stands: two August
// trackers still listing work that had shipped, a build log nobody
// had added a line to in weeks, and a state file whose top entry is
// whatever landed last rather than a summary of anything.
//
// The answer is not a ninth hand-written summary. It is one block at
// the top of STATE.md whose every number is READ from the record it
// summarises, rewritten by a script, and compared byte for byte by a
// test. Nothing in it can be edited into agreement, because nothing
// in it is typed.
//
// The superseded trackers are not deleted. They say so at their own
// first line and point at the file that replaced them, which is the
// same rule this project applies to a superseded measurement.

export const BEGIN_MARKER = "<!-- status:begin -->";
export const END_MARKER = "<!-- status:end -->";

/**
 * The retirement notice a document opens with, or null when its first
 * content line is not one.
 *
 * First line, not anywhere. A notice below a page of prose is a
 * notice the reader reaches after believing the page.
 */
export function retiredNotice(docText) {
  const lines = docText.split("\n");
  let seenHeading = false;
  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed === "") continue;
    if (!seenHeading && trimmed.startsWith("# ")) {
      seenHeading = true;
      continue;
    }
    return trimmed.includes("RETIRED") || trimmed.includes("CLOSED")
      ? trimmed
      : null;
  }
  return null;
}

/**
 * The bundle ceiling, imported rather than parsed. The constant is
 * exported already, so reading the source text for it would be a
 * second, weaker copy of a fact that has a home.
 */
function budgetKb() {
  return (BUNDLE_BUDGET_BYTES / 1000).toFixed(1);
}

/**
 * The status block, built entirely from the record.
 *
 * Every figure here has exactly one home elsewhere in the repository
 * and is read from it: the headline from the current run in the
 * result file, the phase count from ROADMAP's own rows, the suite
 * sizes from the files the runners write. A number that appears in
 * two documents is generated in at least one of them, which is the
 * one rule worth keeping from the audit's process finding.
 */
export function buildStatusBlock(root) {
  const result = parseResultFile(
    readRepoFile("docs/eyeblink8-result.txt", root),
  );
  const phases = phasesComplete(readRepoFile("ROADMAP.md", root));
  const unit = actualUnitTestCount(root);
  const python = actualPythonTestCount(root);
  const ceiling = budgetKb();
  return [
    BEGIN_MARKER,
    "",
    "## Where this project stands",
    "",
    "Generated by `node tools/writeStatusBlock.mjs` from the files that own",
    "each number. Nothing below is typed, so nothing below can be edited into",
    "agreement with a document that has drifted. A test rebuilds this block and",
    "fails when the committed copy differs by a byte.",
    "",
    `- **Phases 0 through ${phases} are complete**, counted from ROADMAP.md's own`,
    "  rows: a phase is finished when every row in it is done, declined, or",
    "  moved.",
    "- **Eyeblink8, the regression harness:** recall " +
      `${result.recallPercent}% (${result.found} of ${result.annotated} found), ` +
      `precision ${result.precisionPercent}% (${result.invented} invented), ` +
      `F1 ${result.f1Percent}%.`,
    "  Read from the current run in",
    "  [docs/eyeblink8-result.txt](docs/eyeblink8-result.txt), which keeps every",
    "  superseded run below it.",
    `- **The suite:** ${unit} unit tests and ${python} Python tests, each figure`,
    "  what its runner collects rather than what a grep counted.",
    `- **The bundle ceiling** is ${ceiling} kB, checked after every build.`,
    "",
    "**The live tracker is [REMEDIATION-2026-09.md](REMEDIATION-2026-09.md).**",
    "`REMEDIATION.md`, `NEEDS-REVIEW.md` and `docs/log.md` are the August",
    "trackers and are retired; each says so at its own first line. They are kept",
    "rather than deleted, which is the same rule this project applies to a",
    "superseded measurement.",
    "",
    END_MARKER,
  ].join("\n");
}

/** Splice a freshly built block over the committed one. */
export function spliceStatusBlock(docText, block) {
  const begin = docText.indexOf(BEGIN_MARKER);
  const end = docText.indexOf(END_MARKER);
  if (begin === -1 || end === -1) {
    throw new Error("STATE.md has no status markers to splice between");
  }
  if (
    docText.indexOf(BEGIN_MARKER, begin + 1) !== -1 ||
    docText.indexOf(END_MARKER, end + 1) !== -1
  ) {
    throw new Error("STATE.md has more than one status block");
  }
  if (end < begin) {
    throw new Error("STATE.md's status markers are in the wrong order");
  }
  return (
    docText.slice(0, begin) + block + docText.slice(end + END_MARKER.length)
  );
}

/** The block as committed, so a test can compare it byte for byte. */
export function committedStatusBlock(docText) {
  const begin = docText.indexOf(BEGIN_MARKER);
  const end = docText.indexOf(END_MARKER);
  if (begin === -1 || end === -1) {
    throw new Error("STATE.md has no status block");
  }
  return docText.slice(begin, end + END_MARKER.length);
}
