import { describe, expect, it } from "vitest";

import {
  BEGIN_MARKER,
  END_MARKER,
  buildStatusBlock,
  committedStatusBlock,
  retiredNotice,
  spliceStatusBlock,
} from "../../tools/statusBlock.mjs";
import { readRepoFile, repoRoot } from "../../tools/resultGuard.mjs";

// Roadmap 10.0b5, ladder D14. The September audit found eight
// documents disagreeing about where this project stands: two August
// trackers still listing items that shipped, a build log nobody has
// written a line in for weeks, and a state file whose top entry is
// whatever landed last rather than a summary.
//
// The answer is not another hand-written summary. It is one block at
// the top of STATE.md whose every number is read from the record it
// summarises, regenerated by a script, and compared byte for byte by
// this test. The three superseded trackers say so at their own first
// line rather than being deleted, because this project keeps what it
// published.

const root = repoRoot();
const state = readRepoFile("STATE.md", root);

describe("splicing the block into a document", () => {
  it("replaces what is between the markers", () => {
    const doc = `head\n${BEGIN_MARKER}\nold\n${END_MARKER}\ntail\n`;
    expect(spliceStatusBlock(doc, `${BEGIN_MARKER}\nnew\n${END_MARKER}`)).toBe(
      `head\n${BEGIN_MARKER}\nnew\n${END_MARKER}\ntail\n`,
    );
  });

  it("refuses a document with no markers", () => {
    expect(() => spliceStatusBlock("head\ntail\n", "x")).toThrow(/markers/);
  });

  it("refuses a document with two blocks", () => {
    const doc = `${BEGIN_MARKER}\na\n${END_MARKER}\n${BEGIN_MARKER}\nb\n${END_MARKER}\n`;
    expect(() => spliceStatusBlock(doc, "x")).toThrow(/more than one/);
  });

  it("refuses markers in the wrong order", () => {
    expect(() =>
      spliceStatusBlock(`${END_MARKER}\n${BEGIN_MARKER}\n`, "x"),
    ).toThrow(/order/);
  });
});

describe("reading a retirement notice", () => {
  it("finds a notice on the document's first content line", () => {
    expect(
      retiredNotice("# Title\n\n**RETIRED 7 September 2026.** See X.\n"),
    ).toContain("RETIRED");
  });

  it("returns null when the notice is buried further down", () => {
    // A notice below a page of prose is a notice a reader reaches
    // after believing the page. It has to be the first thing said.
    expect(
      retiredNotice(
        "# Title\n\nwords\n\nmore\n\n**RETIRED 7 September 2026.**\n",
      ),
    ).toBeNull();
  });
});

describe("the committed block is the generated block", () => {
  it("regenerates byte for byte", () => {
    expect(committedStatusBlock(state)).toBe(buildStatusBlock(root));
  });

  it("carries no placeholder", () => {
    expect(buildStatusBlock(root)).not.toMatch(/TODO|TBD|XXX/);
  });
});

describe("the superseded trackers say so at their first line", () => {
  for (const path of ["REMEDIATION.md", "NEEDS-REVIEW.md", "docs/log.md"]) {
    it(`${path} opens with its retirement notice`, () => {
      const notice = retiredNotice(readRepoFile(path, root));
      expect(
        notice,
        `${path} does not open with a retirement notice`,
      ).not.toBeNull();
      expect(notice).toContain("REMEDIATION-2026-09.md");
    });
  }
});
